"""
app.py – ScrapNet Waste Classification System
==============================================
Run locally:  streamlit run app.py
Deploy:       Push to GitHub → connect to Streamlit Cloud

Expected folder structure (all relative to this file):
    scrapnet_2/
    ├── app.py                   ← this file
    ├── predict.py
    ├── custom_cnn.py
    ├── scrapnet_utils.py
    ├── artifacts/               ← for Streamlit Cloud deployment
    │   ├── efficientnet_b0_waste.pth
    │   ├── classes.json
    │   ├── accuracy_curve.png
    │   ├── loss_curve.png
    │   └── confusion_matrix_normalized.png
    └── experiments/             ← generated by running notebooks
        ├── b0_no_aug/
        ├── b0_aug/
        ├── b3_aug/
        ├── custom_cnn_aug/
        └── comparison/
"""

import os
import json
import sys
from pathlib import Path

import numpy as np
import streamlit as st
from PIL import Image

# ── paths ─────────────────────────────────────────────────────────────────────
BASE_DIR        = Path(__file__).resolve().parent
ARTIFACTS_DIR   = BASE_DIR / "artifacts"
EXPERIMENTS_DIR = BASE_DIR / "experiments"

# Make sure custom_cnn.py and scrapnet_utils.py are importable
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

# ── page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="ScrapNet | Waste Classification",
    page_icon="♻️",
    layout="wide"
)

# ── CSS (your original eco theme) ─────────────────────────────────────────────
st.markdown("""
<style>
.block-container { padding-top: 2rem; }
h1, h2, h3 { color: #1B5E20; }
.stButton>button {
    background-color: #2E7D32;
    color: white;
    border-radius: 8px;
    height: 3em;
}
.stButton>button:hover { background-color: #1B5E20; }
</style>
""", unsafe_allow_html=True)

# ── constants ─────────────────────────────────────────────────────────────────
WASTE_TIPS = {
    "cardboard": "♻️  Flatten boxes and recycle – keep dry!",
    "glass":     "🫙  Rinse bottles and drop in glass bank. No broken glass.",
    "metal":     "🥫  Rinse cans. Most metals are 100% recyclable.",
    "paper":     "📄  Recycle dry paper. Shredded paper goes in compost.",
    "plastic":   "🧴  Check the resin code. Avoid single-use where possible.",
    "trash":     "🗑️  General waste. Try to reduce & reuse before disposing.",
    "compost":   "🌱  Compostable! Goes in the organic/green bin.",
}

ALL_EXPS = {
    "EfficientNet-B0 (no aug)":  ("b0_no_aug",       "b0",         224),
    "EfficientNet-B0 (aug)":     ("b0_aug",          "b0",         224),
    "EfficientNet-B3 (aug)":     ("b3_aug",          "b3",         300),
    "Custom CNN (from scratch)": ("custom_cnn_aug",  "custom_cnn", 224),
}

# ── helpers ───────────────────────────────────────────────────────────────────
def show_img(path, caption=None):
    p = Path(path)
    if p.exists():
        st.image(str(p), caption=caption, use_container_width=True)
    else:
        st.warning(f"Image not found: `{p.name}` — run training notebooks first.")

def load_json(path):
    p = Path(path)
    return json.loads(p.read_text()) if p.exists() else None

def exp_path(exp_name, fname):
    return EXPERIMENTS_DIR / exp_name / fname

# ── model loaders ─────────────────────────────────────────────────────────────
@st.cache_resource(show_spinner="Loading model…")
def load_artifacts_model():
    """Load the artifacts/ model — used when deployed on Streamlit Cloud."""
    from predict import load_model
    return load_model(device="cpu")

@st.cache_resource(show_spinner="Loading model…")
def load_exp_model(exp_name: str, model_type: str):
    """Dynamically load any of the 4 experiment models."""
    import torch
    import torch.nn as nn

    mp = EXPERIMENTS_DIR / exp_name / "model.pth"
    cp = EXPERIMENTS_DIR / exp_name / "classes.json"

    if not mp.exists() or not cp.exists():
        return None, None

    classes = json.loads(cp.read_text())

    if model_type == "custom_cnn":
        from custom_cnn import ScrapNetCNN
        model = ScrapNetCNN(num_classes=len(classes))
    else:
        from torchvision.models import (
            efficientnet_b0, EfficientNet_B0_Weights,
            efficientnet_b3, EfficientNet_B3_Weights,
        )
        if model_type == "b3":
            model = efficientnet_b3(weights=EfficientNet_B3_Weights.DEFAULT)
        else:
            model = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT)
        in_f = model.classifier[1].in_features
        model.classifier[1] = nn.Linear(in_f, len(classes))

    state = torch.load(mp, map_location="cpu")
    model.load_state_dict(state)
    model.eval()
    return model, classes

def predict(model, classes, img: Image.Image, img_size: int):
    import torch
    from torchvision import transforms
    tfms = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    with torch.no_grad():
        probs = torch.softmax(model(tfms(img.convert("RGB")).unsqueeze(0)), dim=1).cpu().numpy()[0]
    idx = int(probs.argmax())
    return classes[idx], float(probs[idx]), probs

# ── sidebar ───────────────────────────────────────────────────────────────────
st.sidebar.title("♻️ ScrapNet")
st.sidebar.caption("AI for Sustainable Waste Management")
st.sidebar.divider()

page = st.sidebar.radio("Navigate", [
    "🏠 Home & Inference",
    "🧠 Custom CNN",
    "📊 Experiment Results",
    "📈 Training Curves",
    "⚖️ Model Comparison",
], label_visibility="collapsed")

st.sidebar.divider()
st.sidebar.markdown("""
**Framework:** PyTorch  
**Transfer Models:** EfficientNet B0/B3  
**Custom Model:** ScrapNetCNN  
**Deployment:** Streamlit Cloud  
""")

# ══════════════════════════════════════════════════════════════
# PAGE 1 — Home & Inference
# ══════════════════════════════════════════════════════════════
if page == "🏠 Home & Inference":
    st.title("♻️ ScrapNet – Waste Classification System")
    st.markdown("A deep learning system for intelligent waste categorisation using transfer learning.")

    st.header("🔬 Model Architecture")
    st.markdown("""
ScrapNet uses **EfficientNet-B0**, a state-of-the-art convolutional neural network
pretrained on ImageNet. The final classification layer was replaced and fine-tuned
on a labelled waste dataset across **7 categories**.
    """)

    st.header("📊 Model Performance")
    col1, col2 = st.columns(2)
    with col1:
        st.markdown("**Accuracy Curve**")
        show_img(ARTIFACTS_DIR / "accuracy_curve.png")
    with col2:
        st.markdown("**Loss Curve**")
        show_img(ARTIFACTS_DIR / "loss_curve.png")
    st.markdown("**Confusion Matrix (Normalized)**")
    show_img(ARTIFACTS_DIR / "confusion_matrix_normalized.png")


    st.header("🧪 Run Inference")

    # Smart model selection: artifacts/ if deployed, otherwise experiments/
    use_artifacts = (ARTIFACTS_DIR / "efficientnet_b0_waste.pth").exists()
    use_exp       = (EXPERIMENTS_DIR / "b0_aug" / "model.pth").exists()

    if not use_artifacts and not use_exp:
        st.error(
            "No model weights found.\n\n"
            "**Option A (deployed):** Add `artifacts/efficientnet_b0_waste.pth` + `artifacts/classes.json`\n\n"
            "**Option B (local):** Run the training notebooks to generate `experiments/b0_aug/model.pth`"
        )
        st.stop()

    if use_artifacts:
        model, classes = load_artifacts_model()
        img_size = 224
    else:
        model, classes = load_exp_model("b0_aug", "b0")
        img_size = 224

    uploaded = st.file_uploader("Upload a waste image", type=["jpg", "jpeg", "png", "webp"])
    if uploaded:
        img = Image.open(uploaded).convert("RGB")
        c1, c2 = st.columns([1, 1])
        with c1:
            st.image(img, caption="Uploaded image", use_container_width=True)
        with c2:
            label, conf, probs = predict(model, classes, img, img_size)
            st.subheader(f"Prediction: **{label}**")
            st.write(f"Confidence: **{conf:.2%}**")
            tip = WASTE_TIPS.get(label.lower())
            if tip:
                st.info(tip)
            topk = np.argsort(probs)[::-1][:3]
            st.markdown("**Top 3 Predictions:**")
            for i in topk:
                st.write(f"- {classes[i]}: {probs[i]:.2%}")

    st.markdown("---")
    st.markdown("© 2026 ScrapNet | AI for Sustainable Waste Management 🌱")


# ══════════════════════════════════════════════════════════════
# PAGE 2 — Custom CNN
# ══════════════════════════════════════════════════════════════
elif page == "🧠 Custom CNN":
    st.title("🧠 Custom CNN – Built From Scratch")
    st.markdown("Unlike EfficientNet, this model learned everything from your waste dataset with no pre-trained weights.")

    st.header("🏗️ Architecture")
    st.code("""
Input  3 × 224 × 224
  │
  ├─ Block 1 ── Conv(3→32)    BatchNorm  ReLU  MaxPool  →  32 × 112 × 112
  ├─ Block 2 ── Conv(32→64)   BatchNorm  ReLU  MaxPool  →  64 × 56  × 56
  ├─ Block 3 ── Conv(64→128)  BatchNorm  ReLU  MaxPool  → 128 × 28  × 28
  ├─ Block 4 ── Conv(128→256) BatchNorm  ReLU  MaxPool  → 256 × 14  × 14
  │
  ├─ Global Average Pooling   →  256-dim vector
  │
  ├─ FC(256→512)  ReLU  Dropout(0.4)
  ├─ FC(512→256)  ReLU  Dropout(0.3)
  └─ FC(256→num_classes)   ← raw logits (softmax applied at inference)
    """, language="text")

    st.header("🔑 Design Decisions")
    col1, col2 = st.columns(2)
    with col1:
        st.markdown("""
| Component | Why |
|---|---|
| **BatchNorm** | Stable training, mild regularisation |
| **ReLU** | Avoids vanishing gradients |
| **MaxPool** | Reduces spatial size, keeps strongest signal |
        """)
    with col2:
        st.markdown("""
| Component | Why |
|---|---|
| **GlobalAvgPool** | Fewer params than Flatten+FC |
| **Dropout 0.4/0.3** | Prevents FC layer overfitting |
| **4 blocks** | Sufficient depth for waste features |
        """)

    summary = load_json(exp_path("custom_cnn_aug", "summary.json"))
    if summary:
        st.header("📊 Results")
        c1, c2, c3 = st.columns(3)
        c1.metric("Best Val Accuracy", f"{summary['best_val_acc']:.2%}")
        c2.metric("Mean F1 Score",     f"{summary['mean_f1']:.4f}")
        c3.metric("Model Type",        "From Scratch")
        st.divider()
        col_a, col_b = st.columns(2)
        with col_a:
            show_img(exp_path("custom_cnn_aug", "confusion_matrix_normalized.png"), "Confusion Matrix")
        with col_b:
            show_img(exp_path("custom_cnn_aug", "f1_scores.png"), "Per-Class F1")
        rp = EXPERIMENTS_DIR / "custom_cnn_aug" / "classification_report.txt"
        if rp.exists():
            with st.expander("📄 Full Classification Report"):
                st.code(rp.read_text())
    else:
        st.info("Train the Custom CNN first by running `scrapnet_cnn.ipynb`.")

    st.header("🧪 Try Custom CNN Inference")
    cnn_model, cnn_classes = load_exp_model("custom_cnn_aug", "custom_cnn")
    if cnn_model is None:
        st.warning("Custom CNN model not found at `experiments/custom_cnn_aug/model.pth`.")
    else:
        up = st.file_uploader("Upload image", type=["jpg","jpeg","png","webp"], key="cnn_up")
        if up:
            img_c = Image.open(up).convert("RGB")
            c1, c2 = st.columns([1,1])
            with c1:
                st.image(img_c, use_container_width=True)
            with c2:
                lbl, cf, prbs = predict(cnn_model, cnn_classes, img_c, 224)
                st.subheader(f"Prediction: **{lbl.upper()}**")
                st.write(f"Confidence: **{cf:.2%}**")
                tip = WASTE_TIPS.get(lbl.lower())
                if tip:
                    st.info(tip)
                topk = np.argsort(prbs)[::-1][:3]
                st.markdown("**Top 3:**")
                for i in topk:
                    st.write(f"- {cnn_classes[i]}: {prbs[i]:.2%}")


# ══════════════════════════════════════════════════════════════
# PAGE 3 — Experiment Results
# ══════════════════════════════════════════════════════════════
elif page == "📊 Experiment Results":
    st.title("📊 Experiment Results")

    exp_label = st.selectbox("Select experiment", list(ALL_EXPS.keys()))
    exp_name, model_type, img_size = ALL_EXPS[exp_label]

    summary = load_json(exp_path(exp_name, "summary.json"))
    if not summary:
        st.warning(f"No results for `{exp_name}`. Run the training notebooks first.")
        st.stop()

    cols = st.columns(4)
    cols[0].metric("Model",        summary["model"].upper())
    cols[1].metric("Augmentation", "Yes" if summary["augment"] else "No")
    cols[2].metric("Best Val Acc", f"{summary['best_val_acc']:.2%}")
    cols[3].metric("Mean F1",      f"{summary['mean_f1']:.4f}")
    st.divider()

    import pandas as pd
    st.subheader("Per-Class F1 Scores")
    f1_df = (pd.DataFrame.from_dict(summary["per_class_f1"], orient="index", columns=["F1 Score"])
             .sort_values("F1 Score", ascending=False))
    st.bar_chart(f1_df)
    st.divider()

    col_a, col_b = st.columns(2)
    with col_a:
        st.subheader("Confusion Matrix (Normalised)")
        show_img(exp_path(exp_name, "confusion_matrix_normalized.png"))
    with col_b:
        st.subheader("F1 Score Chart")
        show_img(exp_path(exp_name, "f1_scores.png"))

    rp = EXPERIMENTS_DIR / exp_name / "classification_report.txt"
    if rp.exists():
        with st.expander("📄 Full Classification Report"):
            st.code(rp.read_text())


# ══════════════════════════════════════════════════════════════
# PAGE 4 — Training Curves
# ══════════════════════════════════════════════════════════════
elif page == "📈 Training Curves":
    st.title("📈 Training Curves")

    exp_label = st.selectbox("Select experiment", list(ALL_EXPS.keys()))
    exp_name  = ALL_EXPS[exp_label][0]

    if not exp_path(exp_name, "loss_curve.png").exists():
        st.warning("Training curves not found. Run the training notebooks first.")
        st.stop()

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Loss")
        show_img(exp_path(exp_name, "loss_curve.png"))
    with col2:
        st.subheader("Accuracy")
        show_img(exp_path(exp_name, "accuracy_curve.png"))

    history = load_json(exp_path(exp_name, "history.json"))
    if history:
        st.divider()
        st.subheader("Interactive Chart")
        import pandas as pd
        hist_df = pd.DataFrame({"Train Acc": history["train_acc"], "Val Acc": history["val_acc"]})
        hist_df.index = hist_df.index + 1
        hist_df.index.name = "Epoch"
        st.line_chart(hist_df)


# ══════════════════════════════════════════════════════════════
# PAGE 5 — Model Comparison
# ══════════════════════════════════════════════════════════════
elif page == "⚖️ Model Comparison":
    st.title("⚖️ All Models Comparison")
    st.caption("Custom CNN (from scratch) vs EfficientNet Transfer Learning")

    import pandas as pd
    rows = []
    for name, (folder, mtype, _) in ALL_EXPS.items():
        s = load_json(EXPERIMENTS_DIR / folder / "summary.json")
        if s:
            rows.append({"Model": name, "Type": "Transfer Learning" if mtype != "custom_cnn" else "From Scratch 🆕",
                         "Best Val Acc": s["best_val_acc"], "Mean F1": s["mean_f1"]})

    if not rows:
        st.warning("No experiment results found. Run the training notebooks first.")
        st.stop()

    df = pd.DataFrame(rows).set_index("Model")
    st.subheader("📋 Summary Table")
    st.dataframe(
        df.style
        .background_gradient(subset=["Best Val Acc", "Mean F1"], cmap="RdYlGn")
        .format({"Best Val Acc": "{:.2%}", "Mean F1": "{:.4f}"}),
        use_container_width=True,
    )
    st.divider()

    comp_dir = EXPERIMENTS_DIR / "comparison"
    plots = [
        ("all_models_comparison.png",   "Val Accuracy & Mean F1 – All 4 Models"),
        ("all_models_per_class_f1.png", "Per-Class F1 – All 4 Models"),
        ("all_models_val_curves.png",   "Validation Curves – All 4 Models"),
        ("model_comparison.png",        "EfficientNet Models – Val Acc & F1"),
        ("per_class_f1_comparison.png", "EfficientNet – Per-Class F1"),
        ("val_curves_overlay.png",      "EfficientNet – Validation Curves"),
    ]
    shown = False
    for fname, title in plots:
        p = comp_dir / fname
        if p.exists():
            st.subheader(title)
            show_img(p)
            shown = True

    if not shown:
        st.info("Run Step 5 in `scrapnet_colab.ipynb` and Step 6 in `scrapnet_cnn.ipynb` to generate comparison plots.")

    st.divider()
    st.subheader("💡 Why Transfer Learning beats Custom CNN")
    col_a, col_b = st.columns(2)
    with col_a:
        st.markdown("""
**Transfer Learning wins because:**
- Pre-trained on 1.2M ImageNet images
- Already knows edges, textures, shapes
- Converges faster with less data
- Less prone to overfitting
        """)
    with col_b:
        st.markdown("""
**Custom CNN still matters because:**
- Teaches exactly how CNNs work
- No external licence dependencies
- Fewer parameters → edge devices
- Fully customisable architecture
        """)
    st.markdown("---")
    st.markdown("© 2026 ScrapNet | AI for Sustainable Waste Management 🌱")
